return {}

-- return {
--   "kevinhwang91/nvim-ufo",
--   dependencies = { "kevinhwang91/promise-async" },
--   open_fold_hl_timeout = 150,
--   close_fold_kinds = { "imports", "comment" },
--   config = function()
--     require("ufo").setup({
--       provider_selector = function(bufnr, filetype, buftype)
--         return { "treesitter", "indent" }
--       end,
--     })
--   end,
--   preview = {
--     win_config = {
--       border = { "", "─", "", "", "", "─", "", "" },
--       winhighlight = "Normal:Folded",
--       winblend = 0,
--     },
--     mappings = {
--       scrollU = "<C-u>",
--       scrollD = "<C-d>",
--       jumpTop = "[",
--       jumpBot = "]",
--     },
--   },
--   provider_selector = function(bufnr, filetype, buftype)
--     -- if you prefer treesitter provider rather than lsp,
--     -- return ftMap[filetype] or {'treesitter', 'indent'}
--     return ftMap[filetype]
--
--     -- refer to ./doc/example.lua for detail
--   end,
-- }
